//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSales
    {
        public int SaleID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Products Products { get; set; }
    }
}
